// Output is committed; re-run only to refresh against a newer Natural Earth.
// The column is FIPS_10 (not FIPS_10_).

import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CACHE = path.join(REPO_ROOT, ".cache", "ne_countries.json");
const OUTPUT = path.join(REPO_ROOT, "data", "crosswalk.json");

const SOURCE_URL =
  "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_admin_0_countries.geojson";

type Feature = {
  properties: {
    FIPS_10?: string;
    ISO_A2?: string;
    ISO_A2_EH?: string;
    NAME?: string;
    CONTINENT?: string;
  };
};

/** Natural Earth writes -99 rather than null for "no value". */
const value = (raw: string | undefined): string => (raw && raw !== "-99" ? raw.trim() : "");

const CONTINENT_NAMES = new Set([
  "Africa",
  "Antarctica",
  "Asia",
  "Europe",
  "North America",
  "Oceania",
  "South America",
]);

const continentOf = (raw: string | undefined): string =>
  raw && CONTINENT_NAMES.has(raw) ? raw : "";

async function naturalEarth(): Promise<Feature[]> {
  await mkdir(path.dirname(CACHE), { recursive: true });
  const cached = await stat(CACHE).catch(() => null);
  if (!cached || cached.size === 0) {
    console.log(`  fetching ${SOURCE_URL}`);
    const response = await fetch(SOURCE_URL);
    if (!response.ok) throw new Error(`Natural Earth: HTTP ${response.status}`);
    await writeFile(CACHE, Buffer.from(await response.arrayBuffer()));
  }
  return JSON.parse(await readFile(CACHE, "utf8")).features as Feature[];
}

async function main(): Promise<void> {
  const features = await naturalEarth();

  const fips: Record<string, { iso: string; name: string; continent: string }> = {};
  const collisions: string[] = [];
  let noIso = 0;
  let noContinent = 0;

  for (const feature of features) {
    const code = value(feature.properties.FIPS_10);
    if (!code) continue;

    // ISO_A2 is -99 for France, Kosovo and a few dependencies; ISO_A2_EH carries their code.
    const iso = value(feature.properties.ISO_A2) || value(feature.properties.ISO_A2_EH);
    const name = value(feature.properties.NAME);
    const continent = continentOf(feature.properties.CONTINENT);
    if (!iso) noIso++;
    if (!continent) noContinent++;

    if (fips[code]) {
      collisions.push(`${code}: ${fips[code].name} / ${name}`);
      continue;
    }
    fips[code] = { iso, name, continent };
  }

  const payload = {
    _comment:
      "GENERATED by scripts/build-crosswalk.ts from Natural Earth ne_10m_admin_0_countries. " +
      "Do not hand-edit — put corrections in data/fips-overrides.json, which is applied on top.",
    source: SOURCE_URL,
    generatedAt: new Date().toISOString().slice(0, 10),
    fips,
  };
  await writeFile(OUTPUT, `${JSON.stringify(payload, null, 2)}\n`, "utf8");

  console.log(`
  features            ${features.length}
  FIPS codes mapped   ${Object.keys(fips).length}
  without an ISO code ${noIso}
  without a continent ${noContinent}
  collisions          ${collisions.length}${collisions.map((c) => `\n    ${c}`).join("")}

  wrote ${path.relative(REPO_ROOT, OUTPUT)}`);

  // Reported, not asserted: the assertion needs data/fips-overrides.json applied, so it lives
  // in worker/refdata.ts.
  const traps: Record<string, string> = { RS: "RU", CH: "CN", IS: "IL", AS: "AU", UK: "GB" };
  console.log("  §3.4 collision codes, before overrides:");
  for (const [code, iso] of Object.entries(traps)) {
    const got = fips[code]?.iso ?? "";
    const mark = got === iso ? "ok" : got === "" ? "MISSING -> needs an override" : "MISMATCH";
    console.log(`    ${code} -> ${got || "(none)"}  expected ${iso}  ${mark}`);
  }
  console.log("");
}

await main();
