/**
 * Generate data/crosswalk.json — the FIPS 10-4 -> ISO 3166 country crosswalk.
 *
 * HANDOFF.md §3.4: GDELT speaks FIPS, everything else speaks ISO, and four codes
 * collide with entirely different countries (RS is Russia, not Serbia; CH is
 * China, not Switzerland; IS is Israel, not Iceland; AS is Australia, not
 * American Samoa). A naive two-letter join is silently wrong and looks correct.
 *
 * Natural Earth carries the mapping in a `FIPS_10` column — note `FIPS_10`, not
 * `FIPS_10_`, which is the name that does not exist and cost this project time
 * once already.
 *
 * Run:  node scripts/build-crosswalk.ts
 * Output is committed. Re-run only to refresh against a newer Natural Earth.
 */

import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CACHE = path.join(REPO_ROOT, ".cache", "ne_countries.json");
const OUTPUT = path.join(REPO_ROOT, "data", "crosswalk.json");

const SOURCE_URL =
  "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_admin_0_countries.geojson";

type Feature = {
  properties: {
    FIPS_10?: string;
    ISO_A2?: string;
    ISO_A2_EH?: string;
    NAME?: string;
  };
};

/** Natural Earth writes -99 rather than null for "no value". */
const value = (raw: string | undefined): string =>
  raw && raw !== "-99" ? raw.trim() : "";

async function naturalEarth(): Promise<Feature[]> {
  await mkdir(path.dirname(CACHE), { recursive: true });
  const cached = await stat(CACHE).catch(() => null);
  if (!cached || cached.size === 0) {
    console.log(`  fetching ${SOURCE_URL}`);
    const response = await fetch(SOURCE_URL);
    if (!response.ok) throw new Error(`Natural Earth: HTTP ${response.status}`);
    await writeFile(CACHE, Buffer.from(await response.arrayBuffer()));
  }
  return JSON.parse(await readFile(CACHE, "utf8")).features as Feature[];
}

async function main(): Promise<void> {
  const features = await naturalEarth();

  const fips: Record<string, { iso: string; name: string }> = {};
  const collisions: string[] = [];
  let noIso = 0;

  for (const feature of features) {
    const code = value(feature.properties.FIPS_10);
    if (!code) continue;

    // ISO_A2 is -99 for France, Kosovo and a few dependencies; ISO_A2_EH carries
    // the de-facto code for those. Sovereignty edge cases (Spratly Islands) have
    // neither, and are kept with an empty ISO rather than dropped — GDELT can
    // still tag a story there, and a known name beats an unknown code.
    const iso = value(feature.properties.ISO_A2) || value(feature.properties.ISO_A2_EH);
    const name = value(feature.properties.NAME);
    if (!iso) noIso++;

    if (fips[code]) {
      collisions.push(`${code}: ${fips[code].name} / ${name}`);
      continue; // first wins; the report below makes the choice visible
    }
    fips[code] = { iso, name };
  }

  const payload = {
    _comment:
      "GENERATED by scripts/build-crosswalk.ts from Natural Earth ne_10m_admin_0_countries. " +
      "Do not hand-edit — put corrections in data/fips-overrides.json, which is applied on top.",
    source: SOURCE_URL,
    generatedAt: new Date().toISOString().slice(0, 10),
    fips,
  };
  await writeFile(OUTPUT, `${JSON.stringify(payload, null, 2)}\n`, "utf8");

  console.log(`
  features            ${features.length}
  FIPS codes mapped   ${Object.keys(fips).length}
  without an ISO code ${noIso}
  collisions          ${collisions.length}${collisions.map((c) => `\n    ${c}`).join("")}

  wrote ${path.relative(REPO_ROOT, OUTPUT)}`);

  // §3.4's collisions, reported rather than asserted. The assertion lives in
  // worker/refdata.ts, which sees the crosswalk with data/fips-overrides.json
  // applied — and it has to, because **Natural Earth has no FIPS_10 for
  // Israel**, which is exactly why the override file exists. Failing here would
  // make the generator unable to produce the input its own fix depends on.
  const traps: Record<string, string> = { RS: "RU", CH: "CN", IS: "IL", AS: "AU", UK: "GB" };
  console.log("  §3.4 collision codes, before overrides:");
  for (const [code, iso] of Object.entries(traps)) {
    const got = fips[code]?.iso ?? "";
    const mark = got === iso ? "ok" : got === "" ? "MISSING -> needs an override" : "MISMATCH";
    console.log(`    ${code} -> ${got || "(none)"}  expected ${iso}  ${mark}`);
  }
  console.log("");
}

await main();
